#!/usr/bin/env bash

# summary
    # this exists so that python for-sure 
    # links to python3 and not python2

# linux is using the system python (for now)
if [[ "$OSTYPE" == "linux-gnu" ]] 
then
    python3 $@
else
    "$PROJECT_FOLDER/.venv/bin/python3" $@
fi