#!/usr/bin/env bash

# 
# enable performance mode
# 
sudo nvpmodel -m 0
sudo jetson_clocks --fan

# allow user to access pins
sudo usermod -a -G dialout "$(whoami)"

# update everything as always
# sudo apt-get update -y
# sudo apt-get upgrade -y

# 
# setup shell hooks
# 
shell_hooks_path="$HOME/shell_hooks/rc"
mkdir -p "$shell_hooks_path"
echo 'export NIXPKGS_ALLOW_UNFREE=1' > "$shell_hooks_path/04_00_00_nix_allow_unfree.bash"
export NIXPKGS_ALLOW_UNFREE=1

echo 'put this in the ~/.bashrc" if its not already there:

for each in $('"$shell_hooks_path"')
do
    . '"$shell_hooks_path"'"/$each"
end
'
echo "Did you check?";read ANSWER;echo
if [ ! "$ANSWER" =~ ^[Yy] ]
then
    echo " >:( "
    exit 1
fi


# 
# setup all the things
# 
./commands/setup/ssh
./commands/setup/zerotier
./commands/setup/cli_tools
./commands/setup/opencv
./commands/setup/onyx
./commands/setup/realsense
./commands/setup/zed