#!/usr/bin/env bash
# if crontab doesnt exist
if [ -z "$(command -v "crontab")" ]
then
    echo 'I dont see the "crontab" command, so I cant setup the boot script'
else
    (crontab -l ; echo "0 * * * * '$HOME'/.boot.sh") | sort - | uniq - | crontab -

    echo '

        # give self access to port (which resets on boot for some reason)
        if [ -f "/dev/ttyTHS0" ]
        then
            sudo -S chmod 777 /dev/ttyTHS0 <<< "tamucv319
        "
        fi

        # then run main file
        python3 "$HOME/repos/cv_main/main/subsystems/communicating/test_pyserial.py"

    ' > "$HOME/.boot.sh"
fi