#!/usr/bin/env bash
# if crontab doesnt exist
if [ -z "$(command -v "crontab")" ]
then
    echo 'I dont see the "crontab" command, so I cant setup the boot script'
else
    kinda_escaped_home="'$HOME/'"
    
    # 
    # pass
    # 
    echo "Please enter the password (yes its plaintext)"
    read PASS
    echo "$PASS" > "$HOME/.pass"
    
    # 
    # cron
    # 
    (crontab -l ; echo "@reboot $HOME/.preboot.sh >> .boot.log") | sort - | uniq - | crontab -
    
    # 
    # preboot (wrapper)
    # 
    zsh_location="'$(which zsh)'"
    echo '
        #!/usr/bin/env bash
        # yes this is dumb
        # yes it is necessary
        '$zsh_location' '$kinda_escaped_home'/.boot.sh &> '$kinda_escaped_home'/.boot.log
    ' > "$HOME/.preboot.sh"
    chmod 777 "$HOME/.preboot.sh"
    
    
    # 
    # boot
    # 
    echo '
        # give self access to port (which resets on boot for some reason)
        echo "trying to give myself access to the port"
        pass="$(cat '$kinda_escaped_home'/.pass)"
        sudo -S usermod -a -G dialout xavier3 <<< "$pass" && echo "gave self access"
        sudo -S nvpmodel -m 0 <<< "$pass"
        sudo -S jetson_clocks --fan <<< "$pass"

        # then run main file
        echo "trying to load zshrc"
        . '$kinda_escaped_home'"/.zshrc"
        echo "trying to run cv_main"
        cd '$kinda_escaped_home'"/repos/cv_main"
        { sleep 1 && python3 '$kinda_escaped_home'"/repos/cv_main/main/main.py" } &
        export PID_OF_MAIN_PY=$!
        
        echo "python stuff is running on: $PID_OF_MAIN_PY"
        # see: https://lwn.net/Articles/317814/
        # if file exists
        if [ -f "/proc/$PID_OF_MAIN_PY/oom_adj" ]
        then
            sudo -S echo '-10' > "/proc/$PID_OF_MAIN_PY/oom_adj" <<< "$pass"
        fi
         
    ' > "$HOME/.boot.sh"
    chmod 777 "$HOME/.boot.sh"
    
    # 
    # link to project
    # 
    ln -s "$HOME/.boot.sh" "$HOME/repos/cv_main/boot.ignore.sh"
    ln -s "$HOME/.boot.log" "$HOME/repos/cv_main/boot.ignore.log"
fi