#!/usr/bin/env bash

echo '
#
# installing onnx
#
'
# Install the prerequisite protobuf
sudo pip3 install protobuf
sudo pip3 install --upgrade protobuf
if [ -f /etc/debian_version ] 
then
    sudo apt-get install protobuf-compiler libprotoc-dev
fi

# Install Onnx
sudo pip3 install onnx==1.4.1