#!/usr/bin/env bash
storage_12GB_in_blocks=12582912
sudo dd if=/dev/zero of=/swapfile bs=1024 count=$storage_12GB_in_blocks status=progress && \
sudo chmod 600 /swapfile && \
ls -l /swapfile && \
sudo mkswap /swapfile && \
sudo swapon -a /swapfile && \
sudo swapon -s