#!/usr/bin/env bash

echo '
#
# checking zerotier
#'
# setup zerotier
# if no zerotier-cli
if ! [ -n "$(command -v "zerotier-cli")" ]
then
    curl -s https://install.zerotier.com | sudo bash
    sudo zerotier-cli join a84ac5c10a5ef3b8
fi