defaultFrom = "ce6aa13369b667ac2542593170993504932eb836" # this is a commit hash on the nixpkgs repo on github for the stable version 22.05 (May 2022)

[config]
allowUnfree = true
permittedInsecurePackages = [ "openssl-1.0.2u",]