#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"$SCRIPT_DIR/exec" main /usr/local/bin/gem "$@"
# if installing a gem, then add it to the gemfile
if [[ "$1" = "install" ]] 
then
    echo "dont forget to update the gemfile!"
    echo '    gem list --local $new_gem | grep $new_gem'
    echo '    bundle add $new_gem $gem_version'
fi