#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

# python cache at any level (half second to rebuild these)
rm -rf **/__pycache__

# all the virtual env pip modules (several minutes to rebuild these)
rm -rf ./

# misc
rm .project_dir.nosync.txt
rm .nosync.pip_modules.hash