#!/usr/bin/env bash

if [ -z "$FORNIX_FOLDER" ]
then
    FORNIX_FOLDER="$PWD"
fi

echo "creating onnx model from yolov4-tiny-416"
cd "$FORNIX_FOLDER/main/subsystems/modeling/model"
python3 yolo_to_onnx.py -m "$FORNIX_FOLDER/main/subsystems/modeling/model/yolov3-tiny-416" --category_num 2