#!/usr/bin/env bash

cd "$HOME"/repos/cv_main/

export process_name="$(python3 -c 'from quik_config import find_and_load;print(find_and_load("main/info.yaml").config.process_name)')"

screen -S "$process_name" -p 0 -X stuff "^C" # stuff is literally the name of the command/option its NOT a placeholder