#!/usr/bin/env bash

# for xavier
if [ -d "$HOME"/repos/cv_main/ ]
then
    cd "$HOME"/repos/cv_main/
fi

export process_name="$(python3 -c 'from quik_config import find_and_load;print(find_and_load("main/info.yaml").config.process_name)')"
export main_folder="$(python3 -c 'from quik_config import find_and_load;print(find_and_load("main/info.yaml").absolute_path_to.main_folder)')"

screen -dm -L -Logfile "$main_folder/MAIN_PY_LOGFILE.ignore.log" -S "$process_name" python3 "$main_folder"/main.py