gcc_cpp_lib_path="$(find -L /nix/store/ -name libstdc++.so.6 | grep -e 'gcc-8.3.0-lib/lib' | head -n 1)"
echo "gcc_path: $gcc_cpp_lib_path"
gcc_lib_path="$(basename "$gcc_cpp_lib_path")"
echo "gcc_lib_path: $gcc_lib_path"
# export LD_LIBRARY_PATH="/nix/store/784rh7jrfhagbkydjfrv68h9x3g4gqmk-gcc-8.3.0-lib/lib:$LD_LIBRARY_PATH"
